package lan.tlab.r4j.jdsql.plugin.builtin.mysql;

import lan.tlab.r4j.jdsql.ast.visitor.PreparedStatementSpecFactory;
import lan.tlab.r4j.jdsql.ast.visitor.ps.PreparedStatementRenderer;
import lan.tlab.r4j.jdsql.dsl.DSL;
import lan.tlab.r4j.jdsql.plugin.SqlDialectPlugin;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MySqlFetchPsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MySqlMergeStatementPsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlCurrentDatePsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlCurrentDateTimePsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlCustomFunctionCallPsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlDateArithmeticRenderStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlEscapeStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlJsonExistsPsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlJsonQueryPsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.ast.visitor.ps.strategy.MysqlJsonValuePsStrategy;
import lan.tlab.r4j.jdsql.plugin.builtin.mysql.dsl.MysqlDSL;

/**
 * Built-in plugin for the MySQL dialect.
 * <p>
 * This plugin provides support for rendering SQL statements according to MySQL syntax
 * and semantics. It leverages MySQL-specific rendering strategies for features such as
 * identifier escaping, pagination, date/time functions, and string operations.
 * <p>
 * <b>What is MySQL?</b>
 * <p>
 * MySQL is an open-source relational database management system (RDBMS) that is widely
 * used in web applications and enterprise systems. This plugin implements MySQL-specific
 * SQL syntax and features, including:
 * <ul>
 *   <li>Backtick identifier escaping (`identifier`) instead of double quotes</li>
 *   <li>LIMIT/OFFSET syntax for pagination</li>
 *   <li>CONCAT() function for string concatenation</li>
 *   <li>DATE_ADD/DATE_SUB for date arithmetic</li>
 *   <li>NOW() and CURDATE() functions for current timestamp and date</li>
 *   <li>LENGTH() function for string/data length operations</li>
 * </ul>
 * <p>
 * <b>MySQL Version Compatibility:</b>
 * <p>
 * This plugin is designed to work with MySQL 8.x and later versions. It uses the semantic
 * version range "^8.0.0" which matches all MySQL 8.x versions (>=8.0.0 and <9.0.0).
 * Many features are also compatible with MySQL 5.7, but the plugin is optimized for
 * MySQL 8.0 and newer.
 * <p>
 * <b>MariaDB Compatibility:</b>
 * <p>
 * MariaDB is a MySQL-compatible fork and many SQL statements generated by this plugin
 * will work correctly with MariaDB. However, this plugin is specifically tuned for
 * MySQL behavior. For production MariaDB deployments, consider creating a dedicated
 * MariaDB plugin if needed.
 * <p>
 * <b>Design Characteristics:</b>
 * <ul>
 *   <li><b>Immutable</b>: This class is a singleton with no mutable state</li>
 *   <li><b>Thread-safe</b>: Can be safely used from multiple threads</li>
 *   <li><b>Stateless</b>: All rendering logic is delegated to the SqlRenderer</li>
 * </ul>
 * <p>
 * <b>Usage Example:</b>
 * <pre>{@code
 * // Automatically discovered via ServiceLoader
 * SqlDialectRegistry registry = SqlDialectRegistry.createWithServiceLoader();
 * Result<PreparedStatementSpecFactory> result = registry.getRenderer("mysql", "8.0.35");
 *
 * // Or created directly
 * SqlDialectPlugin plugin = MySQLDialectPlugin.instance();
 * PreparedStatementSpecFactory specFactory = plugin.createRenderer();
 * }</pre>
 * <p>
 * <b>Version Matching:</b>
 * <p>
 * This plugin uses semantic versioning with the caret range "^8.0.0". This means:
 * <ul>
 *   <li>Matches MySQL 8.0.0, 8.0.1, 8.0.35, 8.1.0, 8.999.999</li>
 *   <li>Does NOT match MySQL 9.0.0 or later (major version change)</li>
 *   <li>Does NOT match MySQL 7.x or earlier</li>
 * </ul>
 * <p>
 * <b>MySQL-Specific Features Implemented:</b>
 * <ul>
 *   <li><b>Identifier Escaping:</b> Uses backticks (`table`.`column`) instead of
 *       standard SQL double quotes</li>
 *   <li><b>Pagination:</b> Uses LIMIT n OFFSET m syntax instead of standard SQL
 *       OFFSET n ROWS FETCH NEXT m ROWS ONLY</li>
 *   <li><b>Current Date:</b> Uses CURDATE() instead of CURRENT_DATE</li>
 *   <li><b>Current Timestamp:</b> Uses NOW() instead of CURRENT_TIMESTAMP</li>
 *   <li><b>Date Arithmetic:</b> Uses DATE_ADD() and DATE_SUB() functions instead of
 *       standard SQL date arithmetic operators</li>
 *   <li><b>String Concatenation:</b> Uses CONCAT() function instead of the || operator</li>
 *   <li><b>Data Length:</b> Uses LENGTH() function for measuring string/data length</li>
 * </ul>
 * <p>
 * <b>Limitations and Notes:</b>
 * <ul>
 *   <li>EXCEPT clause: Only supported in MySQL 8.0.31 and later</li>
 *   <li>Window functions: Fully supported in MySQL 8.0+</li>
 *   <li>CTEs (WITH clause): Fully supported in MySQL 8.0+</li>
 *   <li>For MySQL 5.7 support, some features may require different rendering strategies</li>
 * </ul>
 * <p>
 * <b>ServiceLoader Discovery:</b>
 * <p>
 * This plugin is automatically discovered through Java's {@link java.util.ServiceLoader}
 * mechanism via {@link MysqlDialectPluginProvider}. The provider is registered in
 * {@code META-INF/services/lan.tlab.r4j.sql.plugin.SqlDialectPluginProvider}.
 *
 * @see SqlDialectPlugin
 * @see MysqlDialectPluginProvider
 * @see <a href="https://dev.mysql.com/doc/">MySQL Documentation</a>
 * @see <a href="https://dev.mysql.com/doc/refman/8.0/en/">MySQL 8.0 Reference Manual</a>
 * @since 1.0
 */
public final class MysqlDialectPlugin {

    /**
     * The canonical name for the MySQL dialect.
     * <p>
     * This name is used for plugin registration and lookup in the {@link lan.tlab.r4j.jdsql.plugin.SqlDialectPluginRegistry}.
     * The registry performs case-insensitive matching, so "MySQL", "mysql", and "MYSQL"
     * will all match this dialect.
     */
    public static final String DIALECT_NAME = "MySQL";

    /**
     * The version range of MySQL supported by this plugin.
     * <p>
     * This uses semantic versioning with a caret range "^8.0.0", which means it supports
     * all MySQL 8.x versions (>=8.0.0 and <9.0.0). The registry will perform semantic
     * version matching when resolving this plugin.
     * <p>
     * For exact version requirements or MySQL 5.7 support, additional plugins can be
     * registered with different version ranges.
     */
    public static final String DIALECT_VERSION = "^8.0.0";

    private static final SqlDialectPlugin INSTANCE =
            new SqlDialectPlugin(DIALECT_NAME, DIALECT_VERSION, MysqlDialectPlugin::createMySqlDSL);

    /**
     * Private constructor to prevent instantiation.
     * <p>
     * This class follows the singleton pattern. Use {@link #instance()} to obtain
     * the plugin instance.
     */
    private MysqlDialectPlugin() {
        // Utility class - prevent instantiation
    }

    /**
     * Creates the MySQL-specific renderers.
     * <p>
     * This method creates both the {@link SqlRenderer} and {@link PreparedStatementRenderer}
     * configured specifically for MySQL syntax, including:
     * <ul>
     *   <li>Backtick identifier escaping</li>
     *   <li>LIMIT/OFFSET pagination syntax</li>
     *   <li>CURDATE() for current date</li>
     *   <li>NOW() for current timestamp</li>
     *   <li>DATE_ADD/DATE_SUB for date arithmetic</li>
     * </ul>
     *
     * @return a new {@link PreparedStatementSpecFactory} instance configured for MySQL, never {@code null}
     */
    private static PreparedStatementSpecFactory createMySqlRenderer() {
        PreparedStatementRenderer psRenderer = PreparedStatementRenderer.builder()
                .escapeStrategy(new MysqlEscapeStrategy())
                .currentDateStrategy(new MysqlCurrentDatePsStrategy())
                .currentDateTimeStrategy(new MysqlCurrentDateTimePsStrategy())
                .dateArithmeticStrategy(new MysqlDateArithmeticRenderStrategy())
                .customFunctionCallStrategy(new MysqlCustomFunctionCallPsStrategy())
                .paginationStrategy(new MySqlFetchPsStrategy())
                .jsonExistsStrategy(new MysqlJsonExistsPsStrategy())
                .jsonValueStrategy(new MysqlJsonValuePsStrategy())
                .jsonQueryStrategy(new MysqlJsonQueryPsStrategy())
                .mergeStatementStrategy(new MySqlMergeStatementPsStrategy())
                .build();

        return new PreparedStatementSpecFactory(psRenderer);
    }

    /**
     * Creates a MySQL-specific DSL instance.
     * <p>
     * Returns a {@link MysqlDSL} instance configured with
     * the MySQL renderer. This DSL provides MySQL-specific custom functions like
     * {@code GROUP_CONCAT}, {@code IF}, {@code DATE_FORMAT}, {@code NOW()}, etc.
     * <p>
     * <b>Example usage:</b>
     * <pre>{@code
     * MySQLDSL dsl = (MySQLDSL) MySQLDialectPlugin.instance().createDSL();
     * String sql = dsl.select(
     *     dsl.groupConcat("name", ", ").as("names")
     * ).from("users").build();
     * }</pre>
     *
     * @return a new {@link lan.tlab.r4j.sql.dsl.mysql.MysqlDSL} instance configured for MySQL, never {@code null}
     */
    private static DSL createMySqlDSL() {
        return new MysqlDSL(createMySqlRenderer());
    }

    /**
     * Returns the singleton instance of the MySQL dialect plugin.
     * <p>
     * This method is thread-safe and always returns the same instance. The plugin
     * is immutable and can be safely shared across threads.
     * <p>
     * <b>Example usage:</b>
     * <pre>{@code
     * SqlDialectPlugin plugin = MySQLDialectPlugin.instance();
     * PreparedStatementSpecFactory specFactory = plugin.createRenderer();
     * }</pre>
     *
     * @return the singleton MySQL dialect plugin instance, never {@code null}
     */
    public static SqlDialectPlugin instance() {
        return INSTANCE;
    }
}
